# Generated by Django 5.1.2 on 2024-12-07 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Notification", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificationsettings",
            name="interval_minutes",
            field=models.IntegerField(
                choices=[(45, "45 นาที"), (60, "60 นาที"), (1, " 1 นาที")], default=45
            ),
        ),
    ]
