# Generated by Django 5.1.2 on 2024-11-08 04:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personalhealthinformation",
            name="age",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="personalhealthinformation",
            name="has_pain",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="personalhealthinformation",
            name="height",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="personalhealthinformation",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="personalhealthinformation",
            name="weight",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="personalinformation",
            name="break_hours",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="personalinformation",
            name="goal",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Improve posture", "Improve posture"),
                    ("Health maintenance", "Health maintenance"),
                    ("Posture correction", "Posture correction"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="personalinformation",
            name="job_hours",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="personalinformation",
            name="job_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="personalinformation",
            name="job_type",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
