# Generated by Django 5.1.2 on 2024-11-26 01:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_alter_personalhealthinformation_age_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userusagehistory",
            name="usage_count",
        ),
        migrations.RemoveField(
            model_name="userusagehistory",
            name="user",
        ),
        migrations.AddField(
            model_name="userusagehistory",
            name="posture_detection",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="base.posturedetection",
            ),
        ),
    ]
