# Generated by Django 5.1.2 on 2024-11-27 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_remove_userusagehistory_usage_count_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="posturedetection",
            name="timestamp",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="userusagehistory",
            name="timestamp",
            field=models.DateTimeField(),
        ),
    ]
