# Generated by Django 5.1.2 on 2024-11-27 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0004_alter_posturedetection_timestamp_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="posturedetection",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="userusagehistory",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
