# Generated by Django 5.1.2 on 2024-12-15 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0005_alter_posturedetection_timestamp_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="posturedetection",
            name="detection_time",
        ),
        migrations.AddField(
            model_name="userusagehistory",
            name="detection_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="userusagehistory",
            name="detect_type",
            field=models.CharField(
                choices=[
                    ("Photo Detection", "Photo Detection"),
                    ("Side-part Detection", "Side-part Detection"),
                ],
                max_length=50,
            ),
        ),
    ]
