# Generated by Django 5.1.2 on 2024-12-15 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0006_remove_posturedetection_detection_time_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userusagehistory",
            name="timestamp",
        ),
    ]
