# Generated by Django 5.1.2 on 2024-12-16 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0008_posturedetection_detection_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="posturedetection",
            name="detection_time",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="userusagehistory",
            name="detection_time",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
