# Generated by Django 5.1.2 on 2025-01-13 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0009_alter_posturedetection_detection_time_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="posturedetection",
            name="detection_time",
        ),
        migrations.RemoveField(
            model_name="userusagehistory",
            name="timestamp",
        ),
        migrations.AddField(
            model_name="personalinformation",
            name="age",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="personalinformation",
            name="has_pain",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="personalinformation",
            name="height",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="personalinformation",
            name="weight",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="userusagehistory",
            name="posture_detection",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="base.posturedetection"
            ),
        ),
        migrations.DeleteModel(
            name="PersonalHealthInformation",
        ),
    ]
