# Generated by Django 5.1.2 on 2025-01-18 19:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0011_alter_posturedetection_timestamp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="posturedetection",
            name="timestamp",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 1, 18, 19, 45, 25, 683261, tzinfo=datetime.timezone.utc
                ),
                null=True,
            ),
        ),
    ]
