# Generated by Django 5.1.2 on 2025-01-18 19:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0012_alter_posturedetection_timestamp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="posturedetection",
            name="timestamp",
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
