# Generated by Django 5.1.2 on 2025-02-01 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0013_alter_posturedetection_timestamp"),
    ]

    operations = [
        migrations.DeleteModel(
            name="NotificationLog",
        ),
    ]
